<?php
/**
 * TL_ROOT/system/modules/catalogajaxratingfield/languages/de/tl_catalog_fields.php 
 * 
 * Contao extension: cataloggeocoordsfield 0.1 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Nikolas Runde
 * License   : LGPL 
 * Author    : Nikolas Runde, http://www.nrmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['geocoordsfield'] = "Koordinatenfeld";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geoCoordsTable']['0'] = "Adresstabelle";
$GLOBALS['TL_LANG']['tl_catalog_fields']['geoCoordsTable']['1'] = "Tabelle die die ben&ouml;tigten Adressdaten enth&auml;lt";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_streetfield']['0'] = "Stra&szlig;e und Hausnummer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_streetfield']['1'] = "Geben Sie hier das Feld f&uuml;r die Stra&szlig;e und Hausnummer an";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_postalfield']['0'] = "Postleitzahl";
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_postalfield']['1'] = "Geben Sie hier das Feld f&uuml;r die Postleitzahl an";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_cityfield']['0'] = "Ort";
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_cityfield']['1'] = "Geben Sie hier das Feld f&uuml;r den Ort an";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_countryfield']['0'] = "Land";
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_countryfield']['1'] = "Geben Sie hier das Feld f&uuml;r das Land an";
?>
